name: Typedoc

on:
  push:
    branches:
      - master  # Set a branch name to trigger deployment
      - typedoc-action

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Use Node.js
        uses: actions/setup-node@v1

      - name: Install
        env:
          RUNNING_NODE_CI: 1
        run: npm ci

      - name: Build
        run: npm run build

      - name: Generate
        run: npx lerna run doc:generate

      - name: Deploy - msal-core
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./lib/msal-core/ref
          destination_dir: ./ref/msal-core
          keep_files: true

      - name: Deploy - msal-angular
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./lib/msal-angular/ref
          destination_dir: ./ref/msal-angular
          keep_files: true

      - name: Deploy - msal-browser
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./lib/msal-browser/ref
          destination_dir: ./ref/msal-browser
          keep_files: true

      - name: Deploy - msal-common
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./lib/msal-common/ref
          destination_dir: ./ref/msal-common
          keep_files: true

      - name: Deploy - msal-node
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./lib/msal-node/ref
          destination_dir: ./ref/msal-node
          keep_files: true
